name: Run Petstore Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install project dependencies
        run: npm install

      - name: Run Newman tests
        run: npm run test petstore.collection.json
